using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Avalonia.Plugin.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class MetadataGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. 定义语法提供程序：筛选出所有带有属性的类
            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                    transform: static (ctx, _) => ExtractClassMetadata(ctx))
                .Where(static m => m is not null);

            // 2. 将所有发现的类元数据收集为一个集合
            var collectedMetadata = classProvider.Collect();

            // 3. 注册源码生成输出
            context.RegisterSourceOutput(collectedMetadata, static (spc, classes) => Execute(spc, classes));
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<ClassMetadata> classes)
        {
            if (classes.IsDefaultOrEmpty) return;

            // 寻找带有 [GenerateMetadata] 的目标插件主类
            var targetPlugin = classes.FirstOrDefault(c => c.HasGenerateMetadataAttribute);
            if (targetPlugin == null) return;

            var viewLines = new StringBuilder();
            var navLines = new StringBuilder();
            var menuDataLines = new StringBuilder();

            foreach (var cls in classes)
            {
                // 处理 ViewMap
                if (cls.Attributes.TryGetValue("ViewMap", out var vArgs))
                {
                    viewLines.AppendLine($"            yield return new KeyValuePair<Type, ViewFactory>(typeof({cls.ClassName}), () => new {vArgs[0]}());");
                }

                // 处理 NavigationItem
                if (cls.Attributes.TryGetValue("NavigationItem", out var nArgs))
                {
                    navLines.AppendLine($"            {{ {nArgs[0]}, () => new {cls.ClassName}() }},");
                }

                // 处理 Menu
                if (cls.MenuInfo != null)
                {
                    var m = cls.MenuInfo;
                    menuDataLines.AppendLine($"            allItems.Add(({m.Parent ?? "null"}, new MenuItemViewModel {{ MenuHeader = {m.Header}, Key = {m.Key}, Status = {m.Status ?? "null"}, Order = {m.Order} }}, {m.Order}));");
                }
            }

            var source = GenerateSource(targetPlugin.Namespace, targetPlugin.ClassName, viewLines.ToString(), navLines.ToString(), menuDataLines.ToString());
            context.AddSource($"{targetPlugin.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private static string GenerateSource(string ns, string className, string viewLines, string navLines, string menuLines)
        {
            return $@"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Avalonia.Controls;
using Avalonia.Plugin.Shared;
using Avalonia.Plugin.Shared.ViewModels;
using {ns}.Pages;
using {ns}.ViewModels;

namespace {ns}
{{
    public partial class {className} : IPlugin
    {{
        public IEnumerable<KeyValuePair<Type, ViewFactory>> GetViewDefinitions()
        {{
{viewLines}            yield break;
        }}

        public Dictionary<string, ViewModelFactory> GetNavigationItems() => new Dictionary<string, ViewModelFactory>
        {{
{navLines}
        }};

        public List<KeyValuePair<string, MenuItemViewModel>> GetMenuItems()
        {{
            var allItems = new List<(string? Parent, MenuItemViewModel Item, int Order)>();
{menuLines}

            var itemLookup = allItems.ToDictionary(x => x.Item.RawHeader ?? x.Item.MenuHeader, x => x.Item);
            var missingParents = allItems
                .Where(x => !string.IsNullOrEmpty(x.Parent) && !itemLookup.ContainsKey(x.Parent!))
                .Select(x => x.Parent).Distinct().ToList();

            foreach (var pHeader in missingParents)
            {{
                var virtualParent = new MenuItemViewModel {{ MenuHeader = pHeader!, Key = pHeader! }};
                itemLookup[pHeader!] = virtualParent;
                allItems.Add((null, virtualParent, 0));
            }}

            foreach (var entry in allItems)
            {{
                if (!string.IsNullOrEmpty(entry.Parent) && itemLookup.TryGetValue(entry.Parent!, out var parentNode))
                {{
                    if (!parentNode.Children.Contains(entry.Item))
                        parentNode.Children.Add(entry.Item);
                }}
            }}

            return allItems
                .Where(x => string.IsNullOrEmpty(x.Parent))
                .OrderBy(x => x.Item.Order)
                .Select(x => new KeyValuePair<string, MenuItemViewModel>(null, x.Item))
                .ToList();
        }}
    }}
}}";
        }

        private static ClassMetadata ExtractClassMetadata(GeneratorSyntaxContext context)
        {
            var cls = (ClassDeclarationSyntax)context.Node;
            var className = cls.Identifier.Text;
            var ns = (cls.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault()?.Name.ToString()) ?? "Global";

            var metadata = new ClassMetadata(className, ns);

            foreach (var attrList in cls.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    var attrName = attr.Name.ToString();
                    if (attrName.Contains("GenerateMetadata")) metadata.HasGenerateMetadataAttribute = true;

                    var args = ExtractAttributeArguments(attr);
                    metadata.Attributes[attrName.Replace("Attribute", "")] = args;

                    if (attrName.Contains("Menu"))
                    {
                        metadata.MenuInfo = ParseMenuInfo(attr);
                    }
                }
            }
            return metadata;
        }

        private static List<string> ExtractAttributeArguments(AttributeSyntax attr)
        {
            var results = new List<string>();
            if (attr.ArgumentList == null) return results;

            foreach (var arg in attr.ArgumentList.Arguments)
            {
                var expr = arg.Expression;
                if (expr is TypeOfExpressionSyntax typeofExpr)
                    results.Add(typeofExpr.Type.ToString());
                else
                    results.Add(expr.ToString());
            }
            return results;
        }

        private static MenuInfo ParseMenuInfo(AttributeSyntax attr)
        {
            string header = "null", key = "null", parent = "null", status = "null";
            int order = 100;

            if (attr.ArgumentList != null)
            {
                var args = attr.ArgumentList.Arguments;
                for (int i = 0; i < args.Count; i++)
                {
                    var arg = args[i];
                    var val = arg.Expression.ToString();
                    var name = arg.NameEquals?.Name.Identifier.Text;

                    if (name == null) // 位置参数
                    {
                        if (i == 0) header = val;
                        else if (i == 1) key = val;
                        else if (i == 2) parent = val;
                    }
                    else // 命名参数
                    {
                        switch (name)
                        {
                            case "Header": header = val; break;
                            case "Key": key = val; break;
                            case "ParentKey": parent = val; break;
                            case "Status": status = val; break;
                            case "Order": int.TryParse(val, out order); break;
                        }
                    }
                }
            }
            return new MenuInfo(header, key, parent != "null" ? parent : null, status != "null" ? status : null, order);
        }
    }

    // 用于增量缓存的数据模型，必须是简单的纯数据结构
    internal class ClassMetadata
    {
        public string ClassName { get; }
        public string Namespace { get; }
        public bool HasGenerateMetadataAttribute { get; set; }
        public Dictionary<string, List<string>> Attributes { get; } = new Dictionary<string, List<string>>();
        public MenuInfo MenuInfo { get; set; }
        public ClassMetadata(string name, string ns) { ClassName = name; Namespace = ns; }
    }

    internal class MenuInfo
    {
        public string Header { get; }
        public string Key { get; }
        public string Parent { get; }
        public string Status { get; }
        public int Order { get; }
        public MenuInfo(string h, string k, string p, string s, int o) { Header = h; Key = k; Parent = p; Status = s; Order = o; }
    }
}