using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class MetadataGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        var classNodes = context.Compilation.SyntaxTrees
            .SelectMany(st => st.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>()).ToList();

        var targetPlugin = classNodes.FirstOrDefault(c => HasAttr(c, "GenerateMetadata"));
        if (targetPlugin == null) return;

        string ns = GetNamespace(targetPlugin);
        string className = targetPlugin.Identifier.Text;

        var viewLines = new StringBuilder();
        var navLines = new StringBuilder();
        var menuData = new List<(string Header, string Key, string? Parent, string? Status, int Order, string VMType)>();

        foreach (var cls in classNodes)
        {
            var vmName = cls.Identifier.Text;

            if (TryGetAttr(cls, "ViewMap", out var vAttr))
            {
                var vType = GetArg(vAttr, 0);
                viewLines.AppendLine($"        yield return new KeyValuePair<Type, ViewFactory>(typeof({vmName}), () => new {vType}());");
            }

            if (TryGetAttr(cls, "NavigationItem", out var nAttr))
            {
                var navKey = GetArg(nAttr, 0);
                navLines.AppendLine($"        {{ {navKey}, () => new {vmName}() }},");
            }

            if (TryGetAttr(cls, "Menu", out var mAttr))
            {
                menuData.Add(ParseMenu(mAttr, vmName));
            }
        }

        var menuAddLines = GenerateMenuAddStatements(menuData);

        var source = $@"// <auto-generated />
using System;
using System.Collections.Generic;
using Avalonia.Controls;
using Avalonia.Plugin.Shared;
using Avalonia.Plugin.Shared.ViewModels;

namespace {ns}
{{
    public partial class {className} : IPlugin
    {{
        public IEnumerable<KeyValuePair<Type, ViewFactory>> GetViewDefinitions()
        {{
{viewLines}
        }}

        public Dictionary<string, ViewModelFactory> GetNavigationItems() => new Dictionary<string, ViewModelFactory>
        {{
{navLines}
        }};

        public List<KeyValuePair<string, MenuItemViewModel>> GetMenuItems()
        {{
            var allItems = new List<(string? Parent, MenuItemViewModel Item, int Order)>();
{menuAddLines}
            return MenuItemTreeBuilder.BuildTree(allItems);
        }}
    }}
}}";
        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private string GenerateMenuAddStatements(List<(string Header, string Key, string? Parent, string? Status, int Order, string VMType)> data)
    {
        var sb = new StringBuilder();
        foreach (var d in data)
        {
            sb.AppendLine($@"            allItems.Add(({d.Parent ?? "null"}, new MenuItemViewModel {{ MenuHeader = {d.Header}, Key = {d.Key}, Status = {d.Status ?? "null"}, Order = {d.Order} }}, {d.Order}));");
        }
        return sb.ToString();
    }

    private bool HasAttr(ClassDeclarationSyntax c, string name) =>
        c.AttributeLists.SelectMany(al => al.Attributes).Any(a => a.Name.ToString().Contains(name));

    private bool TryGetAttr(ClassDeclarationSyntax cls, string attrName, out AttributeSyntax? attr)
    {
        attr = cls.AttributeLists
            .SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString().Contains(attrName));

        return attr != null;
    }

    private string GetArg(AttributeSyntax attr, int index)
    {
        if (attr.ArgumentList == null || attr.ArgumentList.Arguments.Count <= index)
            return "null";

        var arg = attr.ArgumentList.Arguments[index].Expression;

        if (arg is TypeOfExpressionSyntax typeofExp)
            return typeofExp.Type.ToString();

        return arg.ToString();
    }

    private string GetNamespace(ClassDeclarationSyntax cls) =>
        (cls.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault()?.Name.ToString()) ?? "Global";

    private (string Header, string Key, string? Parent, string? Status, int Order, string VMType)
    ParseMenu(AttributeSyntax attr, string vmType)
    {
        string header = "null";
        string key = "null";
        string? parent = "null";
        string? status = "null";
        int order = 100;

        if (attr.ArgumentList != null)
        {
            var args = attr.ArgumentList.Arguments;

            if (args.Count >= 1 && args[0].NameEquals == null)
                header = args[0].Expression.ToString();

            if (args.Count >= 2 && args[1].NameEquals == null)
                key = args[1].Expression.ToString();

            if (args.Count >= 3 && args[2].NameEquals == null)
                parent = args[2].Expression.ToString();

            foreach (var arg in args.Where(a => a.NameEquals != null))
            {
                var name = arg.NameEquals!.Name.Identifier.Text;
                var expression = arg.Expression.ToString();

                switch (name)
                {
                    case "Header": header = expression; break;
                    case "Key": key = expression; break;
                    case "ParentKey": parent = expression; break;
                    case "Status": status = expression; break;
                    case "Order":
                        if (!int.TryParse(expression, out order)) order = 100;
                        break;
                }
            }
        }

        return (header, key, parent, status, order, vmType);
    }
}
