using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class MetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetClassProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var hasGenerateMetadata = classDecl.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .Any(a => a.Name.ToString().Contains("GenerateMetadata"));

                    if (!hasGenerateMetadata) return (GeneratorData?)null;

                    var model = ctx.SemanticModel;
                    var allClasses = model.Compilation.SyntaxTrees
                        .SelectMany(st => st.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
                        .ToList();

                    var ns = GetNamespace(classDecl);
                    var className = classDecl.Identifier.Text;

                    var viewLines = new StringBuilder();
                    var navLines = new StringBuilder();
                    var menuData = new List<(string Header, string Key, string? Parent, string? IconName, string? Status, int Order)>();

                    foreach (var cls in allClasses)
                    {
                        var vmName = cls.Identifier.Text;
                        var vmNs = GetNamespace(cls);
                        var fullVmName = $"{vmNs}.{vmName}";

                        if (TryGetAttr(cls, "ViewMap", out var vAttr))
                        {
                            var vTypeShort = GetArg(vAttr!, 0);
                            var vTypeFull = GetFullTypeName(vTypeShort, allClasses);
                            viewLines.AppendLine($"        yield return new KeyValuePair<Type, ViewFactory>(typeof({fullVmName}), () => new {vTypeFull}());");
                        }

                        if (TryGetAttr(cls, "NavigationItem", out var nAttr))
                        {
                            var navKey = GetArg(nAttr!, 0);
                            navLines.AppendLine($"        {{ {navKey}, () => new {fullVmName}() }},");
                        }

                        if (TryGetAttr(cls, "Menu", out var mAttr))
                        {
                            menuData.Add(ParseMenu(mAttr!));
                        }
                    }

                    return new GeneratorData(ns, className, viewLines.ToString(), navLines.ToString(), menuData);
                })
            .Where(x => x != null)
            .Select((x, _) => x!.Value);

        context.RegisterSourceOutput(targetClassProvider, (ctx, data) =>
        {
            var menuAddLines = GenerateMenuAddStatements(data.MenuData);

            var source = $@"// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using Avalonia.Controls;
using Avalonia.Plugin.Shared;
using Avalonia.Plugin.Shared.ViewModels;
using Avalonia.Styling;
using Microsoft.Extensions.DependencyInjection;

namespace {data.Namespace}
{{
    public partial class {data.ClassName} : IPlugin
    {{
        public IEnumerable<KeyValuePair<Type, ViewFactory>> GetViewDefinitions()
        {{
{data.ViewLines}
        }}

        public Dictionary<string, ViewModelFactory> GetNavigationItems() => new Dictionary<string, ViewModelFactory>
        {{
{data.NavLines}
        }};

        public List<KeyValuePair<string?, MenuItemViewModel>> GetMenuItems()
        {{
            var allItems = new List<(string? Parent, MenuItemViewModel Item, int Order)>();
{menuAddLines}
            return MenuItemTreeBuilder.BuildTree(allItems);
        }}

        public IResourceDictionary? GetIconResources() => null;
    }}
}}";
            ctx.AddSource($"{data.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private readonly struct GeneratorData
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string ViewLines { get; }
        public string NavLines { get; }
        public List<(string Header, string Key, string? Parent, string? IconName, string? Status, int Order)> MenuData { get; }

        public GeneratorData(string ns, string className, string viewLines, string navLines,
            List<(string Header, string Key, string? Parent, string? IconName, string? Status, int Order)> menuData)
        {
            Namespace = ns;
            ClassName = className;
            ViewLines = viewLines;
            NavLines = navLines;
            MenuData = menuData;
        }
    }

    private static string GenerateMenuAddStatements(List<(string Header, string Key, string? Parent, string? IconName, string? Status, int Order)> data)
    {
        var sb = new StringBuilder();
        foreach (var d in data)
        {
            var iconNameProp = d.IconName != null ? $", MenuIconName = {d.IconName}" : "";
            sb.AppendLine($@"            allItems.Add(({d.Parent ?? "null"}, new MenuItemViewModel {{ MenuHeader = {d.Header}, Key = {d.Key}{iconNameProp}, Status = {d.Status ?? "null"}, Order = {d.Order} }}, {d.Order}));");
        }
        return sb.ToString();
    }

    private static bool TryGetAttr(ClassDeclarationSyntax cls, string attrName, out AttributeSyntax? attr)
    {
        attr = cls.AttributeLists
            .SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString().Contains(attrName));

        return attr != null;
    }

    private static string GetArg(AttributeSyntax attr, int index)
    {
        if (attr.ArgumentList == null || attr.ArgumentList.Arguments.Count <= index)
            return "null";

        var arg = attr.ArgumentList.Arguments[index].Expression;

        if (arg is TypeOfExpressionSyntax typeofExp)
            return typeofExp.Type.ToString();

        return arg.ToString();
    }

    private static string GetNamespace(ClassDeclarationSyntax cls) =>
        (cls.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault()?.Name.ToString()) ?? "Global";

    private static string GetFullTypeName(string shortName, List<ClassDeclarationSyntax> allClasses)
    {
        foreach (var cls in allClasses)
        {
            if (cls.Identifier.Text == shortName)
            {
                return $"{GetNamespace(cls)}.{shortName}";
            }
        }
        return shortName;
    }

    private static (string Header, string Key, string? Parent, string? IconName, string? Status, int Order)
    ParseMenu(AttributeSyntax attr)
    {
        string header = "null";
        string key = "null";
        string? parent = "null";
        string? iconName = null;
        string? status = "null";
        int order = 100;

        if (attr.ArgumentList != null)
        {
            var args = attr.ArgumentList.Arguments;

            if (args.Count >= 1 && args[0].NameEquals == null)
                header = args[0].Expression.ToString();

            if (args.Count >= 2 && args[1].NameEquals == null)
                key = args[1].Expression.ToString();

            if (args.Count >= 3 && args[2].NameEquals == null)
                parent = args[2].Expression.ToString();

            foreach (var arg in args.Where(a => a.NameEquals != null))
            {
                var name = arg.NameEquals!.Name.Identifier.Text;
                var expression = arg.Expression.ToString();

                switch (name)
                {
                    case "Header": header = expression; break;
                    case "Key": key = expression; break;
                    case "ParentKey": parent = expression; break;
                    case "IconName": iconName = expression; break;
                    case "Status": status = expression; break;
                    case "Order":
                        if (!int.TryParse(expression, out order)) order = 100;
                        break;
                }
            }
        }

        return (header, key, parent, iconName, status, order);
    }
}
