using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class MetadataGenerator : IIncrementalGenerator
{
    private const string GenerateMetadataAttributeName =
        "LYBox.Plugin.Shared.Attributes.GenerateMetadataAttribute";
    private const string ViewMapAttributeName =
        "LYBox.Plugin.Shared.Attributes.ViewMapAttribute";
    private const string NavigationItemAttributeName =
        "LYBox.Plugin.Shared.Attributes.NavigationItemAttribute";
    private const string MenuAttributeName =
        "LYBox.Plugin.Shared.Attributes.MenuAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targetClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateMetadataAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => CreateTarget(attributeContext));

        var viewDefinitions = context.SyntaxProvider.ForAttributeWithMetadataName(
            ViewMapAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => CreateViewDefinition(attributeContext));

        var navigationItems = context.SyntaxProvider.ForAttributeWithMetadataName(
            NavigationItemAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => CreateNavigationItem(attributeContext));

        var menuItems = context.SyntaxProvider.ForAttributeWithMetadataName(
            MenuAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => CreateMenuItem(attributeContext));

        var metadata = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => new PluginMetadataInfo(
                GetMsBuildProperty(provider, "PluginName"),
                GetMsBuildProperty(provider, "PluginVersion"),
                GetMsBuildProperty(provider, "PluginAuthor"),
                GetMsBuildProperty(provider, "PluginDescription"),
                GetMsBuildProperty(provider, "PluginId"),
                GetMsBuildProperty(provider, "MinPluginSdkVersion"),
                GetMsBuildProperty(provider, "PluginKind"),
                GetMsBuildProperty(provider, "PluginWwwroot"),
                GetMsBuildProperty(provider, "PluginEntryPage")));

        var generationInputs = targetClasses
            .Combine(viewDefinitions.Collect())
            .Combine(navigationItems.Collect())
            .Combine(menuItems.Collect())
            .Combine(metadata)
            .Select(static (data, _) => new GeneratorData(
                data.Left.Left.Left.Left,
                data.Left.Left.Left.Right,
                data.Left.Left.Right,
                data.Left.Right,
                data.Right));

        context.RegisterSourceOutput(generationInputs, static (sourceContext, data) =>
        {
            var viewLines = GenerateViewLines(data.ViewDefinitions);
            var navLines = GenerateNavigationLines(data.NavigationItems);
            var menuAddLines = GenerateMenuAddStatements(data.MenuItems);
            var meta = data.Metadata;
            var target = data.Target;

            var metaLines = new StringBuilder();
            metaLines.AppendLine($"        public string Name => {Str(meta.Name ?? target.ClassName)};");
            metaLines.AppendLine($"        public string Version => {Str(meta.Version ?? "1.0.0")};");
            metaLines.AppendLine($"        public string Author => {Str(meta.Author ?? string.Empty)};");
            metaLines.AppendLine($"        public string Description => {Str(meta.Description ?? string.Empty)};");
            metaLines.AppendLine($"        public string PluginId => {Str(meta.PluginId ?? target.ClassName)};");
            metaLines.AppendLine($"        public string MinPluginSdkVersion => {Str(meta.MinSdkVersion ?? "0.0.0")};");

            var baseInterfaces = "IPlugin, IPluginMetadata";
            var webLines = new StringBuilder();
            var webUsing = string.Empty;
            if (string.Equals(meta.Kind, "Web", StringComparison.OrdinalIgnoreCase))
            {
                baseInterfaces += ", IWebPlugin";
                webUsing = "using LYBox.Plugin.Shared.Web;\r\n";
                webLines.AppendLine("        public IWebPluginDescriptor Web => new WebPluginDescriptor(");
                webLines.AppendLine($"            {Str(meta.Wwwroot ?? "wwwroot")}, {Str(meta.EntryPage ?? "index.html")});");
            }

            var source = $@"// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using Avalonia.Controls;
using LYBox.Plugin.Shared;
using LYBox.Plugin.Shared.ViewModels;
{webUsing}using Microsoft.Extensions.DependencyInjection;

namespace {target.Namespace}
{{
    public partial class {target.ClassName} : {baseInterfaces}
    {{
{metaLines}
{webLines}        public IEnumerable<KeyValuePair<Type, ViewFactory>> GetViewDefinitions()
        {{
{viewLines}
        }}

        public Dictionary<string, ViewModelFactory> GetNavigationItems() => new Dictionary<string, ViewModelFactory>
        {{
{navLines}
        }};

        public List<KeyValuePair<string?, MenuItemViewModel>> GetMenuItems()
        {{
            var allItems = new List<(string? Parent, MenuItemViewModel Item, int Order)>();
{menuAddLines}
            return MenuItemTreeBuilder.BuildTree(allItems);
        }}
    }}
}}";

            sourceContext.AddSource(
                $"{target.ClassName}.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static TargetData CreateTarget(GeneratorAttributeSyntaxContext context)
    {
        var target = (INamedTypeSymbol)context.TargetSymbol;
        var targetNamespace = target.ContainingNamespace.IsGlobalNamespace
            ? "Global"
            : target.ContainingNamespace.ToDisplayString();
        return new TargetData(targetNamespace, target.Name);
    }

    private static ViewDefinitionData CreateViewDefinition(GeneratorAttributeSyntaxContext context)
    {
        var viewModelType = ((INamedTypeSymbol)context.TargetSymbol)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var viewType = context.Attributes[0].ConstructorArguments[0].Value as ITypeSymbol;
        return new ViewDefinitionData(
            viewModelType,
            viewType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object");
    }

    private static NavigationItemData CreateNavigationItem(GeneratorAttributeSyntaxContext context)
    {
        var viewModelType = ((INamedTypeSymbol)context.TargetSymbol)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new NavigationItemData(
            viewModelType,
            ToSourceExpression(context.Attributes[0].ConstructorArguments[0]));
    }

    private static MenuItemData CreateMenuItem(GeneratorAttributeSyntaxContext context)
    {
        var attribute = context.Attributes[0];
        var header = GetConstructorArgument(attribute, 0, "null");
        var key = GetConstructorArgument(attribute, 1, "null");
        var parent = GetConstructorArgument(attribute, 2, "null");
        string? iconName = null;
        var status = "null";
        var order = 100;

        foreach (var argument in attribute.NamedArguments)
        {
            switch (argument.Key)
            {
                case "Header": header = ToSourceExpression(argument.Value); break;
                case "Key": key = ToSourceExpression(argument.Value); break;
                case "ParentKey": parent = ToSourceExpression(argument.Value); break;
                case "IconName": iconName = ToSourceExpression(argument.Value); break;
                case "Status": status = ToSourceExpression(argument.Value); break;
                case "Order" when argument.Value.Value is int value: order = value; break;
            }
        }

        return new MenuItemData(header, key, parent, iconName, status, order);
    }

    private static string GenerateViewLines(ImmutableArray<ViewDefinitionData> definitions)
    {
        var builder = new StringBuilder();
        foreach (var definition in definitions)
        {
            builder.AppendLine(
                $"        yield return new KeyValuePair<Type, ViewFactory>(typeof({definition.ViewModelType}), () => new {definition.ViewType}());");
        }
        return builder.ToString();
    }

    private static string GenerateNavigationLines(ImmutableArray<NavigationItemData> items)
    {
        var builder = new StringBuilder();
        foreach (var item in items)
            builder.AppendLine($"        {{ {item.Key}, () => new {item.ViewModelType}() }},");
        return builder.ToString();
    }

    private static string GenerateMenuAddStatements(ImmutableArray<MenuItemData> items)
    {
        var builder = new StringBuilder();
        foreach (var item in items)
        {
            var iconNameProperty = item.IconName is null ? string.Empty : $", MenuIconName = {item.IconName}";
            builder.AppendLine(
                $"            allItems.Add(({item.Parent}, new MenuItemViewModel {{ MenuHeader = {item.Header}, Key = {item.Key}{iconNameProperty}, Status = {item.Status}, Order = {item.Order} }}, {item.Order}));");
        }
        return builder.ToString();
    }

    private static string GetConstructorArgument(AttributeData attribute, int index, string fallback) =>
        attribute.ConstructorArguments.Length > index
            ? ToSourceExpression(attribute.ConstructorArguments[index])
            : fallback;

    private static string ToSourceExpression(TypedConstant constant)
    {
        if (constant.IsNull) return "null";
        return constant.Value switch
        {
            string value => SymbolDisplay.FormatLiteral(value, quote: true),
            char value => SymbolDisplay.FormatLiteral(value, quote: true),
            bool value => value ? "true" : "false",
            IFormattable value => value.ToString(null, CultureInfo.InvariantCulture),
            _ => constant.Value?.ToString() ?? "null"
        };
    }

    private static string? GetMsBuildProperty(AnalyzerConfigOptionsProvider provider, string name) =>
        provider.GlobalOptions.TryGetValue($"build_property.{name}", out var value) ? value : null;

    private static string Str(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private readonly struct GeneratorData(
        TargetData target,
        ImmutableArray<ViewDefinitionData> viewDefinitions,
        ImmutableArray<NavigationItemData> navigationItems,
        ImmutableArray<MenuItemData> menuItems,
        PluginMetadataInfo metadata)
    {
        public TargetData Target { get; } = target;
        public ImmutableArray<ViewDefinitionData> ViewDefinitions { get; } = viewDefinitions;
        public ImmutableArray<NavigationItemData> NavigationItems { get; } = navigationItems;
        public ImmutableArray<MenuItemData> MenuItems { get; } = menuItems;
        public PluginMetadataInfo Metadata { get; } = metadata;
    }

    private readonly struct TargetData(string targetNamespace, string className)
    {
        public string Namespace { get; } = targetNamespace;
        public string ClassName { get; } = className;
    }

    private readonly struct ViewDefinitionData(string viewModelType, string viewType)
    {
        public string ViewModelType { get; } = viewModelType;
        public string ViewType { get; } = viewType;
    }

    private readonly struct NavigationItemData(string viewModelType, string key)
    {
        public string ViewModelType { get; } = viewModelType;
        public string Key { get; } = key;
    }

    private readonly struct MenuItemData(
        string header,
        string key,
        string parent,
        string? iconName,
        string status,
        int order)
    {
        public string Header { get; } = header;
        public string Key { get; } = key;
        public string Parent { get; } = parent;
        public string? IconName { get; } = iconName;
        public string Status { get; } = status;
        public int Order { get; } = order;
    }

    private readonly struct PluginMetadataInfo(
        string? name,
        string? version,
        string? author,
        string? description,
        string? pluginId,
        string? minSdkVersion,
        string? kind,
        string? wwwroot,
        string? entryPage)
    {
        public string? Name { get; } = name;
        public string? Version { get; } = version;
        public string? Author { get; } = author;
        public string? Description { get; } = description;
        public string? PluginId { get; } = pluginId;
        public string? MinSdkVersion { get; } = minSdkVersion;
        public string? Kind { get; } = kind;
        public string? Wwwroot { get; } = wwwroot;
        public string? EntryPage { get; } = entryPage;
    }
}
