using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace LYBox.Plugin.Generators;

/// <summary>
/// 扫描标注 [RpcCommand] 的方法，为每个含此特性的类生成 partial 实现：
///   - 实现 IRpcBindingSource.RegisterBindings：把每个命令以类型化 lambda 注册到 IRpcHost。
/// 设计为反射无关、编译期强类型（借鉴 Tauri #[tauri::command] 的编译期保证）。
/// 要求：含 [RpcCommand] 的类必须声明为 partial，实例命令所在类须有公共无参构造函数。
/// </summary>
[Generator]
public class RpcCommandGenerator : IIncrementalGenerator
{
    private const string AttributeFullyQualifiedName = "LYBox.Plugin.Shared.Attributes.RpcCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullyQualifiedName,
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var methodSym = (IMethodSymbol)ctx.TargetSymbol;
                    string? name = null;
                    var attr = ctx.Attributes.FirstOrDefault();
                    if (attr != null && attr.ConstructorArguments.Length == 1 &&
                        attr.ConstructorArguments[0].Value is string s)
                    {
                        name = s;
                    }
                    else if (attr != null)
                    {
                        foreach (var named in attr.NamedArguments)
                        {
                            if (named.Key == "Name" && named.Value.Value is string ns)
                                name = ns;
                        }
                    }
                    return new CommandSpec(methodSym, name ?? methodSym.Name);
                });

        var allCommands = commands.Collect();

        context.RegisterSourceOutput(allCommands, (ctx, list) =>
        {
            foreach (var grp in list.GroupBy(c => c.Method.ContainingType.ToDisplayString()))
            {
                EmitClass(ctx, grp.ToList());
            }
        });
    }

    private static void EmitClass(SourceProductionContext ctx, List<CommandSpec> list)
    {
        if (list.Count == 0) return;
        var type = list[0].Method.ContainingType;
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var className = type.Name;
        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using LYBox.Plugin.Shared.Rpc;");
        sb.AppendLine();
        if (ns != null) sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {className} : global::LYBox.Plugin.Shared.Rpc.IRpcBindingSource");
        sb.AppendLine("{");

        bool anyInstance = list.Any(c => !c.Method.IsStatic);
        if (anyInstance)
        {
            sb.AppendLine($"    private static readonly {fullName} __instance = new();");
            sb.AppendLine();
        }

        // RegisterBindings
        sb.AppendLine("    public void RegisterBindings(global::LYBox.Plugin.Shared.Rpc.IRpcHost host)");
        sb.AppendLine("    {");
        foreach (var c in list)
        {
            // 命令名用短名（如 GreetAsync），与前端 window.__lybox.rpc('GreetAsync', ...) 一致。
            // 短名冲突时需在 [RpcCommand(Name="...")] 显式指定。
            var id = c.Name;
            var target = c.Method.IsStatic ? fullName : "__instance";
            var isVoid = c.Method.ReturnsVoid;
            var awaitable = IsAwaitable(c.Method.ReturnType);

            sb.AppendLine($"        host.RegisterCommand(\"{id}\", async (args, ct) =>");
            sb.AppendLine("        {");
            for (int i = 0; i < c.Method.Parameters.Length; i++)
            {
                var p = c.Method.Parameters[i];
                var ts = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            var p{i} = {i} < args.Length ? args[{i}].Deserialize<{ts}>() : default;");
            }
            var callArgs = string.Join(", ", c.Method.Parameters.Select((_, i) => $"p{i}"));
            if (isVoid)
            {
                sb.AppendLine($"            {(awaitable ? "await " : "")}{target}.{c.Method.Name}({callArgs});");
                sb.AppendLine("            return null;");
            }
            else if (awaitable)
            {
                sb.AppendLine($"            var __r = await {target}.{c.Method.Name}({callArgs});");
                sb.AppendLine("            return (object?)__r;");
            }
            else
            {
                sb.AppendLine($"            var __r = {target}.{c.Method.Name}({callArgs});");
                sb.AppendLine("            return (object?)__r;");
            }
            sb.AppendLine("        });");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var hintName = ns != null ? $"{ns}.{className}.Rpc.g.cs" : $"{className}.Rpc.g.cs";
        ctx.AddSource(hintName.Replace(' ', '_'), sb.ToString());
    }

    private static bool IsAwaitable(ITypeSymbol type)
    {
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return name.StartsWith("global::System.Threading.Tasks.Task") ||
               name.StartsWith("global::System.Threading.Tasks.ValueTask");
    }

    private readonly struct CommandSpec
    {
        public IMethodSymbol Method { get; }
        public string Name { get; }
        public CommandSpec(IMethodSymbol method, string name) { Method = method; Name = name; }
    }
}
